lang: "fr"
lang_mls: "french"
n_samples: 50
snr_levels: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]
model_id: "facebook/wav2vec2-lv-60-espeak-cv-ft"
espeak_dll: "C:\\Program Files\\eSpeak NG\\libespeak-ng.dll"